// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Element_test: typeof import('./src/components/element_test.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loginbox: typeof import('./src/components/loginbox.vue')['default']
    Nwfbox: typeof import('./src/components/nwfbox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
